import { CustomEvent, TaskCategory, RobotType } from '../types/types';

export const predefinedTasks: CustomEvent[] = [
  {
    id: 1,
    title: 'Cleaning - Zone A',
    start: new Date(2025, 3, 7, 9, 0),
    end: new Date(2025, 3, 7, 10, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: 'Robot A',
  },
  {
    id: 14,
    title: 'Cleaning - Zone B',
    start: new Date(2025, 3, 7, 10, 30),
    end: new Date(2025, 3, 7, 11, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_A,
  },
  {
    id: 14,
    title: 'DailyMaintenance - Charge',
    start: new Date(2025, 3, 7, 11, 0),
    end: new Date(2025, 3, 7, 12, 0),
    type: TaskCategory.DailyMaintenance,
    robotType: RobotType.Robot_A,
  },
  {
    id: 1,
    title: 'Cleaning Task - Zone A',
    start: new Date(2025, 3, 7, 13, 0),
    end: new Date(2025, 3, 7, 14, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_B,
  },
  {
    id: 14,
    title: 'Cleaning Task - Zone B',
    start: new Date(2025, 3, 7, 10, 30),
    end: new Date(2025, 3, 7, 11, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_B,
  },

  {
    id: 2,
    title: 'DailyMaintenance - Charging',
    start: new Date(2025, 3, 7, 11, 0),
    end: new Date(2025, 3, 7, 11, 30),
    type: TaskCategory.DailyMaintenance,
    robotType: RobotType.Robot_B,
  },
  {
    id: 3,
    title: 'System Update',
    start: new Date(2025, 3, 7, 14, 0),
    end: new Date(2025, 3, 7, 14, 30),
    type: TaskCategory.Other,
    robotType: RobotType.Robot_C,
  },
  {
    id: 4,
    title: 'Evening Cleaning - Zone C',
    start: new Date(2025, 3, 8, 18, 0),
    end: new Date(2025, 3, 8, 19, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_B,
  },
  {
    id: 5,
    title: 'Daily Maintenance - Clear robot water',
    start: new Date(2025, 3, 8, 9, 30),
    end: new Date(2025, 3, 8, 10, 15),
    type: TaskCategory.DailyMaintenance,
    robotType: RobotType.Robot_C,
  },
  {
    id: 6,
    title: 'Cleaning - Zone A',
    start: new Date(2025, 3, 9, 13, 0),
    end: new Date(2025, 3, 9, 13, 45),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_A,
  },
  {
    id: 7,
    title: 'Cleaning Task - Zone D',
    start: new Date(2025, 3, 10, 10, 0),
    end: new Date(2025, 3, 10, 11, 0),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_C,
  },
  {
    id: 8,
    title: 'DailyMaintenance - Charging',
    start: new Date(2025, 3, 10, 14, 30),
    end: new Date(2025, 3, 10, 15, 30),
    type: TaskCategory.DailyMaintenance,
    robotType: RobotType.Robot_A,
  },
  {
    id: 9,
    title: 'Software Update',
    start: new Date(2025, 3, 11, 8, 30),
    end: new Date(2025, 3, 11, 9, 30),
    type: TaskCategory.Other,
    robotType: RobotType.Robot_B,
  },
  {
    id: 10,
    title: 'Cleaning Task - Zone A',
    start: new Date(2025, 3, 11, 16, 0),
    end: new Date(2025, 3, 11, 17, 30),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_C,
  },
  {
    id: 11,
    title: 'Daily Maintenance - Charging',
    start: new Date(2025, 3, 12, 10, 0),
    end: new Date(2025, 3, 12, 10, 45),
    type: TaskCategory.DailyMaintenance,
    robotType: RobotType.Robot_B,
  },
  {
    id: 12,
    title: 'Cleaning Task - Zone A',
    start: new Date(2025, 3, 13, 12, 0),
    end: new Date(2025, 3, 13, 12, 30),
    type: TaskCategory.Cleaning_Task,
    robotType: RobotType.Robot_C,
  },
  {
    id: 13,
    title: 'Weekend Standby Mode Test',
    start: new Date(2025, 3, 13, 14, 0),
    end: new Date(2025, 3, 13, 15, 0),
    type: TaskCategory.Other,
    robotType: RobotType.Robot_A,
  },
];
